name: 'Just run the scripts & don't ask questions'
description: 'Run a set of npm scripts'
inputs:
  scripts:
    description: 'npm scripts to run'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'